# Generated by Django 6.0.2 on 2026-02-06 12:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Personel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tc_no', models.CharField(max_length=11, verbose_name='TC Kimlik No')),
                ('telefon', models.CharField(max_length=20, verbose_name='Telefon Numarası')),
                ('ise_giris_tarihi', models.DateField(verbose_name='İşe Giriş Tarihi')),
                ('izin_hakki', models.IntegerField(default=14, verbose_name='Yıllık İzin Hakkı')),
                ('kalan_izin', models.IntegerField(verbose_name='Kalan İzin Günü')),
                ('guncel_avans_borcu', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Güncel Avans Borcu')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AvansTalebi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('miktar', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Miktar')),
                ('tarih', models.DateField(verbose_name='Talep Tarihi')),
                ('aciklama', models.TextField(verbose_name='Açıklama')),
                ('durum', models.CharField(choices=[('Bekliyor', 'Bekliyor'), ('Onaylandı', 'Onaylandı'), ('Reddedildi', 'Reddedildi')], default='Bekliyor', max_length=20, verbose_name='Durum')),
                ('personel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.personel')),
            ],
        ),
    ]
