# Generated by Django 6.0.2 on 2026-02-06 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personel',
            name='tc_no',
            field=models.CharField(max_length=11, unique=True, verbose_name='TC Kimlik No'),
        ),
        migrations.CreateModel(
            name='AvansHareketi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarih', models.DateTimeField(auto_now_add=True)),
                ('hareket_turu', models.CharField(choices=[('TALEP', 'Avans Talebi'), ('ODEME', 'Borç Ödeme'), ('GIRIS', 'İşe Giriş Borcu')], max_length=20)),
                ('miktar', models.DecimalField(decimal_places=2, max_digits=10)),
                ('onceki_borc', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('yeni_borc', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('aciklama', models.TextField(blank=True)),
                ('personel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.personel')),
            ],
            options={
                'ordering': ['-tarih'],
            },
        ),
    ]
