# Generated by Django 6.0.2 on 2026-02-06 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_personel_tc_no_avanshareketi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personel',
            name='kalan_izin',
            field=models.IntegerField(default=0, verbose_name='Kalan İzin Günü'),
        ),
        migrations.AlterField(
            model_name='personel',
            name='telefon',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefon Numarası'),
        ),
    ]
