# Generated by Django 6.0.2 on 2026-02-06 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_personel_kalan_izin_alter_personel_telefon'),
    ]

    operations = [
        migrations.AddField(
            model_name='personel',
            name='adres',
            field=models.TextField(blank=True, default='', verbose_name='Adres'),
        ),
        migrations.AddField(
            model_name='personel',
            name='pozisyon',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Pozisyon'),
        ),
    ]
