# Generated by Django 6.0.2 on 2026-02-06 17:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_personel_adres_personel_pozisyon'),
    ]

    operations = [
        migrations.AddField(
            model_name='personel',
            name='dogum_tarihi',
            field=models.DateField(blank=True, null=True, verbose_name='Doğum Tarihi'),
        ),
        migrations.CreateModel(
            name='IzinTalebi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslangic_tarihi', models.DateField(verbose_name='Başlangıç Tarihi')),
                ('bitis_tarihi', models.DateField(verbose_name='Bitiş Tarihi')),
                ('gun_sayisi', models.IntegerField(verbose_name='İzin Günü Sayısı')),
                ('aciklama', models.TextField(blank=True, verbose_name='Açıklama')),
                ('durum', models.CharField(choices=[('Bekliyor', 'Bekliyor'), ('Onaylandı', 'Onaylandı'), ('Reddedildi', 'Reddedildi')], default='Bekliyor', max_length=20, verbose_name='Durum')),
                ('talep_tarihi', models.DateTimeField(auto_now_add=True)),
                ('admin_notu', models.TextField(blank=True, verbose_name='Admin Notu')),
                ('personel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.personel')),
            ],
        ),
    ]
