# Generated by Django 6.0.2 on 2026-02-06 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_personel_dogum_tarihi_izintalebi'),
    ]

    operations = [
        migrations.AddField(
            model_name='personel',
            name='profil_tipi',
            field=models.CharField(choices=[('Personel', 'Personel'), ('Muhasebe', 'Muhasebe'), ('Patron', 'Patron')], default='Personel', max_length=20, verbose_name='Profil Tipi'),
        ),
    ]
