# Generated by Django 6.0.2 on 2026-02-07 19:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_personel_profil_tipi'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasrafTalebi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('miktar', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Masraf Tutarı (TL)')),
                ('aciklama', models.TextField(verbose_name='Masraf Açıklaması')),
                ('fis_fatura', models.ImageField(blank=True, null=True, upload_to='fis_faturalar/', verbose_name='Fiş/Fatura Resmi')),
                ('tarih', models.DateField(verbose_name='Masraf Tarihi')),
                ('talep_tarihi', models.DateTimeField(auto_now_add=True, verbose_name='Talep Tarihi')),
                ('durum', models.CharField(choices=[('Bekliyor', 'Bekliyor'), ('Onaylandı', 'Onaylandı'), ('Reddedildi', 'Reddedildi')], default='Bekliyor', max_length=20, verbose_name='Durum')),
                ('admin_notu', models.TextField(blank=True, verbose_name='Admin Notu')),
                ('personel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.personel')),
            ],
        ),
    ]
