# Generated by Django 6.0.2 on 2026-02-09 19:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_masraf_talebi'),
    ]

    operations = [
        migrations.CreateModel(
            name='Egitim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('egitim_adi', models.CharField(max_length=200, verbose_name='Eğitim Adı')),
                ('tarih', models.DateField(verbose_name='Eğitim Tarihi')),
                ('sure', models.CharField(blank=True, max_length=50, verbose_name='Süre')),
                ('durum', models.CharField(choices=[('Tamamlandı', 'Tamamlandı'), ('Devam Ediyor', 'Devam Ediyor'), ('Bekliyor', 'Bekliyor')], default='Bekliyor', max_length=20, verbose_name='Durum')),
                ('aciklama', models.TextField(blank=True, verbose_name='Açıklama')),
                ('personel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='egitimler', to='core.personel')),
            ],
        ),
        migrations.CreateModel(
            name='Zimmet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('malzeme', models.CharField(max_length=200, verbose_name='Malzeme Adı')),
                ('tarih', models.DateField(verbose_name='Zimmet Tarihi')),
                ('durum', models.CharField(choices=[('Aktif', 'Aktif'), ('Iade Edildi', 'Iade Edildi'), ('Zarar Gördü', 'Zarar Gördü')], default='Aktif', max_length=20, verbose_name='Durum')),
                ('aciklama', models.TextField(blank=True, verbose_name='Açıklama')),
                ('personel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zimmetler', to='core.personel')),
            ],
        ),
    ]
