# Generated by Django 6.0.2 on 2026-02-12 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_egitim_zimmet'),
    ]

    operations = [
        migrations.AddField(
            model_name='personel',
            name='aktif',
            field=models.BooleanField(default=True, verbose_name='Aktif'),
        ),
        migrations.AddField(
            model_name='personel',
            name='arsivlenme_nedeni',
            field=models.TextField(blank=True, default='', verbose_name='Arşivlenme Nedeni'),
        ),
        migrations.AddField(
            model_name='personel',
            name='arsivlenme_tarihi',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Arşivlenme Tarihi'),
        ),
    ]
