# Generated by Django 6.0.2 on 2026-02-12 09:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_personel_aktif_personel_arsivlenme_nedeni_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personel',
            name='yonetici',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.personel', verbose_name='Yönetici'),
        ),
        migrations.AlterField(
            model_name='avanstalebi',
            name='durum',
            field=models.CharField(choices=[('Bekliyor', 'Bekliyor'), ('Yonetici Onaylandı', 'Yönetici Onayladı'), ('Muhasebe Onaylandı', 'Muhasebe Onayladı'), ('Reddedildi', 'Reddedildi')], default='Bekliyor', max_length=20, verbose_name='Durum'),
        ),
        migrations.AlterField(
            model_name='izintalebi',
            name='durum',
            field=models.CharField(choices=[('Bekliyor', 'Bekliyor'), ('Yonetici Onaylandı', 'Yönetici Onayladı'), ('Muhasebe Onaylandı', 'Muhasebe Onayladı'), ('Reddedildi', 'Reddedildi')], default='Bekliyor', max_length=20, verbose_name='Durum'),
        ),
        migrations.AlterField(
            model_name='masraftalebi',
            name='durum',
            field=models.CharField(choices=[('Bekliyor', 'Bekliyor'), ('Yonetici Onaylandı', 'Yönetici Onayladı'), ('Muhasebe Onaylandı', 'Muhasebe Onayladı'), ('Reddedildi', 'Reddedildi')], default='Bekliyor', max_length=20, verbose_name='Durum'),
        ),
    ]
